# Generated by Django 4.1 on 2024-09-18 03:26
#makemigrations会在当前目录下生成一个migrations文件夹，该文件夹的内容就是数据库要执行的内容
"""本迁移文件将在数据库中为模型Topic创建一个表"""
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
